
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 52
#define YY_END_OF_BUFFER 53
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[269] =
    {   0,
        0,    0,    0,    0,   53,   51,   48,   49,   48,   45,
       42,   45,   47,    2,    3,    1,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   45,   52,   48,   49,    0,
       43,    0,   47,   44,   44,   44,   46,   44,   44,   44,
       44,   44,   44,   44,   44,   12,   41,   13,   44,   44,
       44,   44,   44,   17,    7,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,

       44,   44,   44,   44,   41,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
        0,   50,   50,    6,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   36,   44,   31,   44,    8,
       44,   44,   44,   44,   44,   27,   44,   44,   44,    9,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   36,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   38,   44,
       44,   44,   44,   39,   10,   44,   22,   44,   44,   19,
       16,   24,   14,   44,   44,   44,   44,   35,   44,   44,

       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   40,
       44,   44,   44,   44,    4,   44,    5,   44,   25,   44,
       11,   44,   44,   44,   23,   44,   44,   44,   44,   44,
       44,   44,   11,   44,   44,   44,   29,   44,   26,   15,
       18,   44,   21,   34,   28,   20,   44,   44,   44,   44,
       44,   30,   37,   44,   32,   32,   33,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    1,    1,    8,    1,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   19,   20,   21,
       22,   23,   24,    1,   25,   26,   27,   28,   29,   30,
       31,   32,   33,   34,   35,   36,   37,   38,   39,   40,
       41,   42,   43,   44,   45,   46,   47,   48,   49,   41,
       50,    1,   51,    1,   41,    1,   52,   53,   54,   55,

       56,   57,   58,   59,   60,   61,   62,   63,   64,   65,
       66,   67,   41,   68,   69,   70,   71,   72,   73,   74,
       75,   41,   76,    1,   77,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[78] =
    {   0,
        1,    1,    1,    1,    2,    1,    2,    1,    2,    2,
        2,    1,    1,    2,    2,    2,    1,    3,    2,    1,
        1,    1,    1,    1,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    1,
        1,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    5,    5
    } ;

static yyconst flex_int16_t yy_base[275] =
    {   0,
        0,    0,    0,    0,  106, 1245,   76, 1245,   80, 1245,
       79,   89,   83, 1245, 1245, 1245,   61,   69,   71,   73,
       75,   77,   79,   82,   87,   89,   92,   96,   98,  115,
      106,  149,  109,  144,  152,  112,  142,  124,  175,  179,
      162,  177,  192,  194,  186,  188,  206,  219,  190,  199,
      222,  228,  255,  261,  215,    0, 1245,  127, 1245,   83,
     1245,  195,   78,    0,  209,  275,    0,  270,  279,  282,
      284,  297,  288,  292,  300,  294,  305,  302,  308,  317,
      312,  336,  326,  332,  339,  354,  357,  365,  374,  368,
      379,  383,  377,  381,  396,  345,  386,  408,  410,  401,

      406,  414,  419,  422,  443,  429,  417,  447,  452,  458,
      456,  479,  482,  484,  491,  489,  493,  496,  512,  507,
      199, 1245,   91,  500,  509,  519,  525,  546,  533,  560,
      563,  531,  574,  576,  586,  579,  581,  572,  588,  594,
      598,  596,  606,  603,  609,  611,  613,  623,  629,  615,
      648,  650,  627,  658,  643,  660,  663,  666,  676,  678,
      680,  683,  690,  692,  695,  698,  700,  710,  723,  714,
      705,  732,  720,  726,  740,  744,  747,  762,  765,  776,
      787,  780,  789,  767,  792,  796,  794,  804,  807,  800,
      809,  811,  814,  816,  829,  818,  832,  827,  849,  856,

      878,  843,  881,  861,  864,  871,  883,  893,  896,  898,
      900,  904,  909,  911,  926,  913,  928,  932,  943,  917,
      949,  924,  977,  953,  921,  974,  934,  989,  994,  996,
      998, 1003, 1005, 1009, 1015, 1020, 1017, 1027, 1029, 1025,
     1031, 1039, 1041, 1044, 1050, 1037, 1046, 1069, 1059, 1066,
     1072, 1106, 1093, 1110, 1112, 1114, 1116, 1126, 1121, 1132,
     1134, 1129, 1136, 1138, 1141, 1147, 1143, 1245, 1224, 1228,
     1230, 1232, 1237, 1240
    } ;

static yyconst flex_int16_t yy_def[275] =
    {   0,
      268,    1,  269,  269,  268,  268,  268,  268,  268,  268,
      270,  268,  268,  268,  268,  268,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  272,  268,  268,  268,  270,
      268,  273,  268,  274,  271,  271,  272,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,

      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      273,  268,  268,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,

      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,    0,  268,  268,
      268,  268,  268,  268
    } ;

static yyconst flex_int16_t yy_nxt[1323] =
    {   0,
        6,    7,    8,    9,    7,   10,   11,   10,   11,   10,
       10,   10,   10,   10,   12,   10,   10,   13,   10,   10,
       14,   15,   16,   10,   17,   18,   19,   20,   21,   22,
       23,   23,   24,   25,   26,   27,   23,   28,   29,   30,
       23,   31,   32,   33,   34,   35,   36,   23,   23,   10,
       10,   37,   38,   39,   40,   41,   42,   23,   23,   43,
       44,   45,   46,   23,   47,   48,   49,   50,   51,   52,
       53,   54,   55,   23,   23,   56,   56,   58,   64,   58,
       58,   58,   59,   58,   58,   61,   64,   61,   64,   61,
       64,   61,   64,  122,   64,   63,   64,   71,   66,   64,

       63,   72,   69,   62,   64,  268,   64,   68,  268,   64,
      268,   76,   70,   64,   73,   64,  268,   80,   75,   77,
       81,  268,   74,   64,   78,   79,   64,  268,   58,   64,
       58,   58,   64,   91,   82,   84,   67,   67,   88,   85,
       83,   64,   86,   95,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   87,   67,   67,   64,
      268,   64,   67,   67,   67,   67,   64,   67,   67,   64,
      268,   67,   67,   67,   67,  268,   94,   89,  268,   64,
       90,   67,   67,   92,   67,   67,   93,   67,   67,   97,
       67,   67,   64,  268,   64,  268,   64,  122,  123,   67,

       67,  122,  123,   64,  268,   64,   96,   64,  268,   64,
      268,   64,  268,  268,  268,  268,   64,   67,   67,   67,
       67,  268,  268,   64,   67,   67,   64,   67,   67,  268,
      100,  268,   64,   98,  101,  103,   64,   67,   67,   64,
      268,  107,   99,  108,  104,   64,  102,  268,   76,  268,
       67,   67,   67,   67,   67,   67,  105,  112,  113,  106,
       78,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       67,  109,   64,  120,   67,   67,  110,  114,   64,  116,
      115,   67,   67,   84,   67,   67,   85,   64,  268,  111,
       67,   67,   64,  268,   67,   67,   64,   67,   67,   64,

      268,   64,  124,   67,   67,   64,  268,  126,  125,   64,
      127,   64,  119,  268,   64,  268,  268,   64,  268,   64,
      268,  117,   64,  118,  132,   64,  131,  128,  268,   64,
       67,   67,  129,  268,   64,  268,   67,   67,  133,  130,
      137,  139,  134,   64,  268,   67,   67,  135,  136,   64,
       67,   67,  268,   64,   67,   67,   64,   67,   67,   67,
       67,  141,   64,   67,   67,  138,  268,   67,   67,   67,
       67,   64,   67,   67,   64,   67,   67,   67,   67,  140,
       67,   67,   64,   67,   67,   64,  268,   67,   67,  143,
      268,   64,   67,   67,   64,  144,   64,  142,   64,  124,

       64,   67,   67,   64,  148,  150,  147,   67,   67,  145,
      149,   67,   67,   64,   67,   67,  151,  146,   64,  268,
       67,   67,  152,   64,  153,   64,  268,   64,  268,   67,
       67,   64,   67,   67,   64,  268,   64,  268,  268,   64,
       67,   67,  268,   67,   67,  268,   64,  268,  268,   67,
       67,  154,   67,   67,   67,   67,   67,   67,   67,   67,
       64,   67,   67,  155,   64,  156,  268,  268,  158,   64,
      157,   67,   67,   64,  159,   64,   67,   67,  161,  160,
      268,   67,   67,   67,   67,   67,   67,  162,  166,   67,
       67,  138,   67,   67,   67,   67,   64,   67,   67,   64,

      268,   64,  268,  167,   67,   67,   64,  163,   64,  268,
       64,  164,  165,   64,  268,  268,  268,   64,   67,   67,
      168,  140,   67,   67,   64,  169,   64,   67,   67,   64,
      268,   67,   67,   67,   67,  268,   64,  268,  170,  171,
      268,  174,   64,  268,  179,  180,  172,  175,   64,  181,
       64,  150,  268,  146,   67,   67,  173,   67,   67,   67,
       67,  183,  178,   64,   67,   67,   67,   67,   67,   67,
      182,   67,   67,  186,  176,   67,   67,   64,  268,  177,
       64,  268,   67,   67,   67,   67,  184,   67,   67,   64,
      268,   64,  268,   64,   67,   67,   64,  268,   64,  268,

       67,   67,  185,   64,  188,   64,   67,   67,   67,   67,
      187,   64,  268,   64,  189,   64,  268,  190,  191,  268,
       64,   67,   67,   64,  194,  268,   64,  268,   64,  268,
       64,  192,   64,  193,  196,   67,   67,  197,   67,   67,
       64,  268,  195,  268,   64,  268,   64,   67,   67,   67,
       67,   67,   67,  200,   67,   67,   67,   67,  199,  198,
       64,   67,   67,   67,   67,   64,  268,   64,  203,   67,
       67,   67,   67,   67,   67,   64,  202,   64,   67,   67,
       64,   67,   67,   64,   67,   67,   67,   67,   67,   67,
       67,   67,  201,   64,  268,   64,  204,   64,   67,   67,

       64,  268,   67,   67,   67,   67,  268,   64,  268,   64,
      268,  205,   64,  268,  206,   64,  268,   64,   67,   67,
      179,  207,   64,   67,   67,   67,   67,   64,  268,  184,
      268,   64,  268,   67,   67,   67,   67,   64,   67,   67,
       64,   67,   67,   64,  185,  209,  187,  210,  208,   64,
      268,   67,   67,   67,   67,   67,   67,   64,   67,   67,
      190,   64,  191,  213,   64,   67,   67,   67,   67,  192,
       67,   67,  193,   67,   67,   67,   67,  212,  211,   64,
       67,   67,   64,  268,   64,   67,   67,  214,  215,   67,
       67,  216,  198,   64,  268,   67,   67,   64,   67,   67,

      218,   67,   67,  268,   64,  222,   64,   67,   67,   64,
      220,   64,  268,   64,  217,   67,   67,   64,  268,   67,
       67,   64,   67,   67,   64,  268,   64,  268,   64,  219,
      221,   64,  223,   64,  268,   64,  268,   67,   67,  224,
       67,   67,   67,   67,   64,  225,   64,  268,  226,   64,
      268,   67,   67,  228,  268,   67,   67,  227,  230,  268,
       64,  229,   67,   67,   67,   67,   64,   67,   67,   67,
       67,   67,   67,   64,  234,   67,   67,  231,   64,   67,
       67,   64,   67,   67,   67,   67,   67,   67,   64,   67,
       67,   67,   67,   67,   67,   64,  268,  268,   64,  232,

       64,  268,   67,   67,   67,   67,  233,   67,   67,  235,
       64,  268,  268,   64,  268,   64,  268,   64,   67,   67,
      268,   64,  220,  237,   67,   67,   64,  268,   64,  268,
       64,   67,   67,  236,   64,  268,   67,   67,   64,   67,
       67,   64,  268,   64,  268,   64,   67,   67,  248,   64,
      268,   64,  238,   67,   67,  241,   67,   67,   67,   67,
       64,  268,  239,  225,  242,  240,   64,  227,   67,   67,
       64,   67,   67,   67,   67,   67,   67,  247,  229,   67,
       67,  243,  244,  245,   67,   67,   67,   67,   67,   67,
      246,   64,   67,   67,   64,  250,   67,   67,  235,   67,

       67,   67,   67,   67,   67,  249,   64,   67,   67,   67,
       67,   64,  268,   64,  268,   64,  268,  251,   67,   67,
       64,  268,   64,  268,   67,   67,   64,  268,   67,   67,
      252,  255,   64,  257,   64,  268,  268,   64,  268,  253,
      254,  268,   64,  268,   64,  268,   64,  256,   64,   67,
       67,  268,   67,   67,   64,  268,   64,  268,   64,  268,
      268,   64,  268,   64,   67,   67,  268,   64,  258,   67,
       67,   67,   67,   67,   67,  247,   64,  268,   67,   67,
       67,   67,  249,   64,   67,   67,   64,  268,  260,   64,
       67,   67,   67,   67,  251,   67,   67,  250,  259,  255,

       67,   67,   67,   67,   67,   67,   67,   67,  253,  254,
       64,  261,   67,   67,   67,   67,   67,   67,  256,   67,
       67,   67,   67,   64,  268,   67,   67,   64,  268,   64,
      268,   64,  268,   64,   67,   67,  268,  268,   64,  268,
      268,   67,   67,   64,   67,   67,   64,   67,   67,   64,
      268,   64,  268,   64,  262,   64,  268,  263,   64,  268,
       64,  268,  265,  268,   64,  268,  268,  268,   67,   67,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,   67,   67,  267,  268,   67,   67,   67,   67,   67,
       67,   67,   67,  266,  264,  262,   67,   67,  268,  263,

      268,   67,   67,  268,   67,   67,  268,   67,   67,   67,
       67,   67,   67,   67,   67,  267,   67,   67,   67,   67,
      268,  268,   67,   67,   57,   57,   57,   57,   57,   60,
       60,   60,   65,   65,   65,   67,   67,  121,  121,  121,
      121,  121,   64,   64,    5,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,

      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268
    } ;

static yyconst flex_int16_t yy_chk[1323] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    7,   17,    7,
        7,    9,    9,    9,    9,   11,   18,   11,   19,   60,
       20,   60,   21,  123,   22,   63,   23,   20,   17,   24,

       13,   20,   19,   12,   25,    5,   26,   18,    0,   27,
        0,   24,   19,   28,   20,   29,    0,   26,   22,   24,
       27,    0,   21,   31,   24,   25,   33,    0,   58,   36,
       58,   58,   30,   33,   28,   29,   17,   17,   31,   29,
       28,   38,   29,   36,   18,   18,   19,   19,   20,   20,
       21,   21,   22,   22,   23,   23,   30,   24,   24,   37,
        0,   34,   25,   25,   26,   26,   32,   27,   27,   35,
        0,   28,   28,   29,   29,    0,   35,   32,    0,   41,
       32,   31,   31,   34,   33,   33,   34,   36,   36,   38,
       30,   30,   39,    0,   42,    0,   40,   62,   62,   38,

       38,  121,  121,   45,    0,   46,   37,   49,    0,   43,
        0,   44,    0,    0,    0,    0,   50,   37,   37,   34,
       34,    0,    0,   47,   32,   32,   65,   35,   35,    0,
       40,    0,   55,   39,   40,   41,   48,   41,   41,   51,
        0,   45,   39,   46,   42,   52,   40,    0,   43,    0,
       39,   39,   42,   42,   40,   40,   43,   49,   50,   44,
       43,   45,   45,   46,   46,   49,   49,   43,   43,   44,
       44,   47,   53,   55,   50,   50,   47,   51,   54,   52,
       51,   47,   47,   48,   65,   65,   48,   68,    0,   48,
       55,   55,   66,    0,   48,   48,   69,   51,   51,   70,

        0,   71,   66,   52,   52,   73,    0,   69,   68,   74,
       70,   76,   54,    0,   72,    0,    0,   75,    0,   78,
        0,   53,   77,   53,   74,   79,   73,   71,    0,   81,
       53,   53,   72,    0,   80,    0,   54,   54,   75,   72,
       79,   81,   77,   83,    0,   68,   68,   77,   77,   84,
       66,   66,    0,   82,   69,   69,   85,   70,   70,   71,
       71,   83,   96,   73,   73,   80,    0,   74,   74,   76,
       76,   86,   72,   72,   87,   75,   75,   78,   78,   82,
       77,   77,   88,   79,   79,   90,    0,   81,   81,   87,
        0,   89,   80,   80,   93,   88,   91,   86,   94,   96,

       92,   83,   83,   97,   91,   93,   90,   84,   84,   89,
       92,   82,   82,   95,   85,   85,   94,   89,  100,    0,
       96,   96,   94,  101,   95,   98,    0,   99,    0,   86,
       86,  102,   87,   87,  107,    0,  103,    0,    0,  104,
       88,   88,    0,   90,   90,    0,  106,    0,    0,   89,
       89,   97,   93,   93,   91,   91,   94,   94,   92,   92,
      105,   97,   97,   98,  108,   99,    0,    0,  101,  109,
      100,   95,   95,  111,  101,  110,  100,  100,  103,  102,
        0,  101,  101,   98,   98,   99,   99,  104,  106,  102,
      102,  107,  107,  107,  103,  103,  112,  104,  104,  113,

        0,  114,    0,  108,  106,  106,  116,  105,  115,    0,
      117,  105,  105,  118,    0,    0,    0,  124,  105,  105,
      110,  109,  108,  108,  120,  111,  125,  109,  109,  119,
        0,  111,  111,  110,  110,    0,  126,    0,  112,  113,
        0,  116,  127,    0,  125,  126,  114,  117,  132,  127,
      129,  118,    0,  114,  112,  112,  115,  113,  113,  114,
      114,  129,  120,  128,  116,  116,  115,  115,  117,  117,
      128,  118,  118,  132,  119,  124,  124,  130,    0,  119,
      131,    0,  120,  120,  125,  125,  130,  119,  119,  138,
        0,  133,    0,  134,  126,  126,  136,    0,  137,    0,

      127,  127,  131,  135,  134,  139,  132,  132,  129,  129,
      133,  140,    0,  142,  135,  141,    0,  136,  137,    0,
      144,  128,  128,  143,  142,    0,  145,    0,  146,    0,
      147,  139,  150,  141,  144,  130,  130,  145,  131,  131,
      148,    0,  143,    0,  153,    0,  149,  138,  138,  133,
      133,  134,  134,  149,  136,  136,  137,  137,  148,  147,
      155,  135,  135,  139,  139,  151,    0,  152,  153,  140,
      140,  142,  142,  141,  141,  154,  152,  156,  144,  144,
      157,  143,  143,  158,  145,  145,  146,  146,  147,  147,
      150,  150,  151,  159,    0,  160,  155,  161,  148,  148,

      162,    0,  153,  153,  149,  149,    0,  163,    0,  164,
        0,  156,  165,    0,  157,  166,    0,  167,  155,  155,
      154,  158,  171,  151,  151,  152,  152,  168,    0,  159,
        0,  170,    0,  154,  154,  156,  156,  173,  157,  157,
      169,  158,  158,  174,  160,  163,  162,  164,  161,  172,
        0,  159,  159,  160,  160,  161,  161,  175,  162,  162,
      165,  176,  166,  171,  177,  163,  163,  164,  164,  167,
      165,  165,  168,  166,  166,  167,  167,  170,  169,  178,
      171,  171,  179,    0,  184,  168,  168,  172,  174,  170,
      170,  175,  173,  180,    0,  173,  173,  182,  169,  169,

      177,  174,  174,    0,  181,  182,  183,  172,  172,  185,
      180,  187,    0,  186,  176,  175,  175,  190,    0,  176,
      176,  188,  177,  177,  189,    0,  191,    0,  192,  178,
      181,  193,  183,  194,    0,  196,    0,  178,  178,  186,
      179,  179,  184,  184,  198,  188,  195,    0,  189,  197,
        0,  180,  180,  195,    0,  182,  182,  194,  197,    0,
      202,  196,  181,  181,  183,  183,  199,  185,  185,  187,
      187,  186,  186,  200,  202,  190,  190,  199,  204,  188,
      188,  205,  189,  189,  191,  191,  192,  192,  206,  193,
      193,  194,  194,  196,  196,  201,    0,    0,  203,  200,

      207,    0,  198,  198,  195,  195,  201,  197,  197,  203,
      208,    0,    0,  209,    0,  210,    0,  211,  202,  202,
        0,  212,  204,  206,  199,  199,  213,    0,  214,    0,
      216,  200,  200,  205,  220,    0,  204,  204,  225,  205,
      205,  222,    0,  215,    0,  217,  206,  206,  222,  218,
        0,  227,  207,  201,  201,  212,  203,  203,  207,  207,
      219,    0,  208,  209,  214,  210,  221,  211,  208,  208,
      224,  209,  209,  210,  210,  211,  211,  221,  213,  212,
      212,  215,  216,  217,  213,  213,  214,  214,  216,  216,
      218,  226,  220,  220,  223,  224,  225,  225,  219,  222,

      222,  215,  215,  217,  217,  223,  228,  218,  218,  227,
      227,  229,    0,  230,    0,  231,    0,  226,  219,  219,
      232,    0,  233,    0,  221,  221,  234,    0,  224,  224,
      228,  232,  235,  234,  237,    0,    0,  236,    0,  230,
      231,    0,  240,    0,  238,    0,  239,  233,  241,  226,
      226,    0,  223,  223,  246,    0,  242,    0,  243,    0,
        0,  244,    0,  247,  228,  228,    0,  245,  237,  229,
      229,  230,  230,  231,  231,  236,  249,    0,  232,  232,
      233,  233,  238,  250,  234,  234,  248,    0,  246,  251,
      235,  235,  237,  237,  240,  236,  236,  239,  241,  244,

      240,  240,  238,  238,  239,  239,  241,  241,  242,  243,
      253,  248,  246,  246,  242,  242,  243,  243,  245,  244,
      244,  247,  247,  252,    0,  245,  245,  254,    0,  255,
        0,  256,    0,  257,  249,  249,    0,    0,  259,    0,
        0,  250,  250,  258,  248,  248,  262,  251,  251,  260,
        0,  261,    0,  263,  252,  264,    0,  257,  265,    0,
      267,    0,  261,    0,  266,    0,    0,    0,  253,  253,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,  252,  252,  265,    0,  254,  254,  255,  255,  256,
      256,  257,  257,  264,  258,  259,  259,  259,    0,  260,

        0,  258,  258,    0,  262,  262,    0,  260,  260,  261,
      261,  263,  263,  264,  264,  266,  265,  265,  267,  267,
        0,    0,  266,  266,  269,  269,  269,  269,  269,  270,
      270,  270,  271,  271,  271,  272,  272,  273,  273,  273,
      273,  273,  274,  274,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,

      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      268,  268
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lex.l"
/*  lexer file
    author: dpatrickx*/
#line 5 "lex.l"
    #include "main.h"
    #include "yacc.tab.h"
    extern "C"
    {
        int yywrap(void);
        int yylex(void);
    }

#line 852 "lex.yy.c"

#define INITIAL 0
#define COMMENT 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 27 "lex.l"

#line 1042 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 269 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1245 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 28 "lex.l"
{   yylval.m_sId = ">";         return JUDGEOP;     }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 29 "lex.l"
{   yylval.m_sId = "<";         return JUDGEOP;     }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 30 "lex.l"
{   yylval.m_sId = "=";         return JUDGEOP;     }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 31 "lex.l"
{   yylval.m_sId = "inner";     return IOKIND;      }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 32 "lex.l"
{   yylval.m_sId = "outer";     return IOKIND;      }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 33 "lex.l"
{   yylval.m_sId = "and";       return CONNOP;      }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 34 "lex.l"
{   yylval.m_sId = "or";        return CONNOP;      }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 35 "lex.l"
{   yylval.m_sId = "not";       return CONNOP;      }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 36 "lex.l"
{   yylval.m_sId = "use";       return USE;         }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 37 "lex.l"
{   yylval.m_sId = "drop";      return DROP;        }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 38 "lex.l"
{   yylval.m_sId = "table";     return TABLE;       }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 39 "lex.l"
{   yylval.m_sId = "if";        return IF;          }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 40 "lex.l"
{   yylval.m_sId = "is";        return IS;          }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 41 "lex.l"
{   yylval.m_sId = "null";      return NULLL;        }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 42 "lex.l"
{   yylval.m_sId = "exists";    return EXISTS;      }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 43 "lex.l"
{   yylval.m_sId = "join";      return JOIN;        }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 44 "lex.l"
{   yylval.m_sId = "on";        return ON;          }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 45 "lex.l"
{   yylval.m_sId = "insert";    return INSERT;      }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 46 "lex.l"
{   yylval.m_sId = "into";      return INTO;        }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 47 "lex.l"
{   yylval.m_sId = "values";    return VALUES;      }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 48 "lex.l"
{   yylval.m_sId = "select";    return SELECT;      }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 49 "lex.l"
{   yylval.m_sId = "from";      return FROM;        }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 50 "lex.l"
{   yylval.m_sId = "where";     return WHERE;       }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 51 "lex.l"
{   yylval.m_sId = "left";      return KIND;        }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 52 "lex.l"
{   yylval.m_sId = "right";     return KIND;        }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 53 "lex.l"
{   yylval.m_sId = "delete";    return DELETE;      }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 54 "lex.l"
{   yylval.m_sId = "set";       return SET;         }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 55 "lex.l"
{   yylval.m_sId = "update";    return UPDATE;      }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 56 "lex.l"
{   yylval.m_sId = "create";    return CREATE;      }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 57 "lex.l"
{   yylval.m_sId = "primary";   return PRIMARY;     }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 58 "lex.l"
{   yylval.m_sId = "key";       return KEY;         }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 59 "lex.l"
{   yylval.m_sId = "database";  return DATABASE;    }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 60 "lex.l"
{   yylval.m_sId = "databases"; return DATABASES;   }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 61 "lex.l"
{   yylval.m_sId = "tables";    return TABLES;      }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 62 "lex.l"
{   yylval.m_sId = "show";      return SHOW;        }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 63 "lex.l"
{   yylval.m_sId = "int";       return TYPE;        }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 64 "lex.l"
{   yylval.m_sId = "varchar";   return TYPE;        }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 65 "lex.l"
{   yylval.m_sId = "bool";      return TYPE;        }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 66 "lex.l"
{   yylval.m_sId = "desc";      return DESC;        }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 67 "lex.l"
{   yylval.m_sId = "check";     return CHECK;       }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 68 "lex.l"
{   yylval.m_sId = "in";        return IN;          }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 69 "lex.l"
{
            yylval.m_sId = yytext;
            return YIN;
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 73 "lex.l"
{
            yylval.m_sId = yytext;
            return VALUEIT;
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 77 "lex.l"
{
            yylval.m_sId = yytext;
            return IDENTIFIER;
        }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 81 "lex.l"
{
            yylval.m_sId = yytext;
            return (int)yytext[0];
        }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 85 "lex.l"
{
            yylval.m_sId = yytext;
            return EXPRESSION;
        }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 89 "lex.l"
{
            yylval.m_sId = yytext;
            return INTEGER;
        }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 93 "lex.l"
{}
	YY_BREAK
case 49:
/* rule 49 can match eol */
YY_RULE_SETUP
#line 94 "lex.l"
{}
	YY_BREAK
case 50:
/* rule 50 can match eol */
YY_RULE_SETUP
#line 95 "lex.l"
{}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 97 "lex.l"
{
            yylval.m_cOp=yytext[0];
            return OPERATOR;
        }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 102 "lex.l"
ECHO;
	YY_BREAK
#line 1408 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 269 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 269 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 268);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 102 "lex.l"


int yywrap(void)
{
    puts("-----the file is end");
    return 1;
}
