
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 43
#define YY_END_OF_BUFFER 44
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[246] =
    {   0,
        0,    0,    0,    0,   44,   42,   39,   40,   39,   36,
       32,   36,   36,   38,    2,    3,    1,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   36,   43,   39,   40,    0,   34,
        0,    0,   38,    0,   35,   35,   35,   37,   35,   35,
       35,   35,   35,   35,   12,   35,   35,   35,   35,   35,
       15,    7,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,

       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   33,    0,   41,   41,    6,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   28,
       35,    8,   35,   35,   35,   35,   24,   35,   35,   35,
        9,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,    8,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   10,   35,   20,
       35,   35,   17,   14,   22,    0,   35,   35,   35,   35,
       31,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,    0,   35,   35,   35,   35,   35,   35,   35,   35,

       35,   35,   35,   35,    4,   35,    0,    5,   35,   35,
       11,   35,   35,   21,   35,   35,   35,   35,   35,    0,
       35,   35,   35,   35,   26,   35,   23,   13,   16,    0,
       35,   19,   25,   18,   35,    0,   35,   35,    0,   27,
       35,    0,   30,   29,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    1,    1,    8,    1,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   19,   20,   21,
       22,   23,   24,    1,   25,   26,   27,   28,   29,   30,
       31,   32,   33,   34,   35,   36,   37,   38,   39,   40,
       41,   42,   43,   44,   45,   46,   47,   48,   49,   41,
       50,    1,   51,    1,   41,    1,   52,   53,   54,   55,

       56,   57,   58,   59,   60,   61,   62,   63,   64,   65,
       66,   67,   41,   68,   69,   70,   71,   72,   73,   74,
       75,   41,   76,    1,   77,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[78] =
    {   0,
        1,    1,    1,    1,    2,    1,    2,    1,    2,    3,
        2,    1,    1,    2,    2,    2,    1,    4,    2,    1,
        1,    1,    1,    1,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    1,
        1,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    6,    6
    } ;

static yyconst flex_int16_t yy_base[252] =
    {   0,
        0,    0,    0,    0,  183, 1462,   76, 1462,   80, 1462,
       79,  160,  158,  149, 1462, 1462, 1462,   69,   79,   81,
       83,   85,   88,   99,   92,   95,  109,  104,  132,  169,
      116,  122,  172,  178,  185,  194,  129,  197,  204,  209,
      214,  219,  221,  223,  232,  226,  248,  259,  241,  294,
      296,  310,  305,  316,    0, 1462,  116, 1462,   83, 1462,
       93,  112,  148,  145,    0,  312,  319,    0,  322,  334,
      328,  344,  351,  358,  331,  399,  396,  384,  406,  408,
      412,  421,  430,  435,  428,  459,  439,  437,  452,  461,
      481,  490,  446,  476,  448,  492,  516,  521,  523,  536,

      554,  532,  560,  565,  569,  567,  576,  585,  592,  601,
      605,  608,  610,  614, 1462,  132, 1462,  150,  639,  641,
      670,  665,  653,  679,  682,  691,  694,  688,  714,  703,
      716,  726,  733,  735,  751,  756,  730,  739,  763,  779,
      766,  777,  795,  807,  811,  790,  813,  816,  831,  820,
      826,  840,  847,  850,  859,  863,  868,  852,  881,  891,
      900,  895,  904,  915,  938,  920,  941,  924,  943,  931,
      952,  956,  968,  985,  992,  114,  994, 1006, 1003, 1012,
     1016, 1025, 1028, 1030, 1045, 1039, 1042, 1055, 1057, 1067,
     1080,   83, 1090, 1076, 1093, 1119, 1128, 1102, 1131, 1137,

     1165, 1167, 1170, 1158, 1141, 1172,   99, 1144, 1188, 1179,
     1192, 1209, 1214, 1218, 1221, 1227, 1240, 1242, 1244,   70,
     1256, 1253, 1249, 1262, 1260, 1265, 1271, 1274, 1283,   92,
     1297, 1292, 1317, 1334, 1339,   37, 1343, 1346,   60, 1348,
     1353,   31, 1360, 1462, 1462, 1437, 1442, 1445, 1447, 1453,
     1456
    } ;

static yyconst flex_int16_t yy_def[252] =
    {   0,
      245,    1,  246,  246,  245,  245,  245,  245,  245,  245,
      247,  245,  245,  245,  245,  245,  245,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  249,  245,  245,  245,  247,  245,
      245,  250,  245,  245,  251,  248,  248,  249,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,

      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  245,  250,  245,  245,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  245,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  245,  248,  248,  248,  248,  248,  248,  248,  248,

      248,  248,  248,  248,  248,  248,  245,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  245,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  245,
      248,  248,  248,  248,  248,  245,  248,  248,  245,  248,
      248,  245,  248,  245,    0,  245,  245,  245,  245,  245,
      245
    } ;

static yyconst flex_int16_t yy_nxt[1540] =
    {   0,
        6,    7,    8,    9,    7,   10,   11,   10,   11,   12,
       10,   10,   10,   10,   13,   10,   10,   14,   10,   10,
       15,   16,   17,   10,   18,   19,   20,   21,   22,   23,
       19,   19,   24,   25,   26,   27,   19,   28,   29,   30,
       19,   31,   32,   33,   34,   35,   36,   19,   19,   10,
       10,   37,   19,   38,   39,   40,   41,   19,   19,   42,
       43,   44,   45,   19,   46,   47,   48,   49,   50,   51,
       52,   53,   54,   19,   19,   55,   55,   57,   64,   57,
       57,   57,   58,   57,   57,   60,   65,   60,   64,   60,
       64,   60,   64,  244,   64,  244,   65,   64,   65,  242,

       65,   64,   65,  115,   64,   65,   67,   70,   64,   65,
       61,   71,   65,   64,  117,  118,   65,   57,   64,   57,
       57,   65,   69,   78,   72,   64,   65,  239,   75,   74,
       77,   64,   73,   65,  117,  118,   76,   79,   64,   65,
      236,   64,   80,  230,   68,   68,   65,  220,   85,   65,
       86,  207,  117,   87,   68,   68,   68,   68,   68,   68,
       68,   68,   61,   68,   68,   63,   63,   68,   68,   81,
       68,   68,   62,   82,   68,   68,   83,   61,   64,   68,
       68,   64,  245,  245,   68,   68,   65,   64,  245,   65,
      245,   68,   68,   93,   64,   65,   88,   68,   68,  245,

      245,  245,   65,   64,   68,   68,   64,   68,   68,   91,
       84,   65,  245,   64,   65,  245,  245,   89,   64,  245,
       90,   65,  245,   64,  245,   92,   65,  245,   64,  245,
       64,   65,   64,  245,  245,   64,   65,  245,   65,  245,
       65,   64,  245,   65,   68,   68,  245,   68,   68,   65,
       64,  245,  245,   68,   68,   95,  245,   64,   65,   96,
       68,   68,  245,  245,   94,   65,  245,  245,   64,   68,
       68,   97,   68,   68,  245,   75,   65,  245,  102,   68,
       68,   99,   98,  100,   68,   68,  101,  103,  245,   68,
       68,  104,  245,  245,   68,   68,   68,   68,   68,   68,

      107,   68,   68,   64,  245,   64,  245,   68,   68,  245,
      245,   65,   81,   65,   64,   82,   68,   68,  105,   64,
      245,   64,   65,   68,   68,   64,  106,   65,   64,   65,
      245,   64,  245,   65,   68,   68,   65,   64,  245,   65,
       64,  245,  245,   64,  245,   65,  119,  110,   65,  108,
      120,   65,  109,   64,  245,  245,  113,  245,  245,  245,
       64,   65,  245,  122,  245,  245,  245,   64,   65,   68,
       68,   68,   68,  245,  114,   65,  111,  121,  112,  245,
       68,   68,  123,  124,  245,   68,   68,   68,   68,  245,
      245,   68,   68,   64,   68,   68,  125,   68,   68,  245,

      245,   65,  245,   68,   68,   64,   68,   68,   64,   68,
       68,  245,  245,   65,  245,   64,   65,   64,  245,   68,
       68,   64,  245,   65,  245,   65,   68,   68,  129,   65,
       64,  245,  130,   68,   68,  131,  126,   64,   65,   64,
      245,  127,  128,  245,   64,   65,   64,   65,   64,  245,
      245,  132,   65,  245,   65,   64,   65,   64,  135,   68,
       68,   64,  139,   65,  245,   65,  245,  134,   64,   65,
       64,   68,   68,  133,   68,   68,   65,  138,   65,  140,
      245,   68,   68,   68,   68,   64,  245,   68,   68,  141,
       64,  245,  245,   65,  136,  245,   68,   68,   65,   64,

      119,   64,  137,   68,   68,   68,   68,   65,  245,   65,
       68,   68,   68,   68,   68,   68,  142,  145,  143,  245,
      245,   68,   68,   68,   68,   64,  245,   68,   68,  245,
       64,  144,   64,   65,   68,   68,   68,   68,   65,  245,
       65,   64,  245,  245,  245,   64,  245,  245,  245,   65,
      245,   68,   68,   65,  146,  245,   68,   68,  245,  245,
      245,  245,  245,   64,  245,   68,   68,   68,   68,   64,
      245,   65,  245,  245,   64,  245,   64,   65,   64,  245,
      148,  147,   65,  245,   65,   64,   65,  245,  149,  245,
      245,   68,   68,   65,   64,  245,   68,   68,   68,   68,

      150,   64,   65,  245,  151,  152,  130,   68,   68,   65,
       64,   68,   68,  153,   64,  245,  154,   64,   65,   64,
      245,  245,   65,   64,  245,   65,  157,   65,  245,   68,
       68,   65,  245,  158,  155,   68,   68,  245,  156,  245,
       68,   68,   68,   68,   68,   68,  245,  159,   64,  245,
       64,   68,   68,  161,  137,  245,   65,  160,   65,  162,
       68,   68,   64,  141,  245,  165,  245,   68,   68,  164,
       65,  245,  163,  245,   64,  245,   68,   68,  245,   64,
       68,   68,   65,   68,   68,   68,   68,   65,   64,   68,
       68,   64,  168,  167,  166,  245,   65,   64,  245,   65,

       64,  245,  245,   64,  245,   65,  245,  245,   65,  245,
      245,   65,   64,  245,   68,   68,   68,   68,  170,  171,
       65,  169,  172,   64,  245,   64,  173,  245,   68,   68,
      176,   65,  245,   65,  245,   64,  245,  245,  245,   64,
       68,   68,   64,   65,   64,   68,   68,   65,   64,  245,
       65,  174,   65,  245,   68,   68,   65,   68,   68,  175,
       64,  177,  245,   68,   68,   64,   68,   68,   65,   68,
       68,  178,   64,   65,  245,   64,  245,  245,   68,   68,
       65,  245,  179,   65,  180,  181,   64,  245,   64,   68,
       68,   68,   68,  245,   65,  245,   65,  245,  182,   64,

      245,   68,   68,  183,   64,   68,   68,   65,   68,   68,
       68,   68,   65,  245,   68,   68,   64,  245,  245,  245,
       64,  184,   64,  245,   65,   64,   68,   68,   65,   64,
       65,   68,   68,   65,  245,   64,  185,   65,   68,   68,
       64,   68,   68,   65,  245,  188,  245,  245,   65,   64,
      245,  245,   68,   68,   68,   68,   64,   65,  186,   64,
      245,   64,  187,  192,   65,   68,   68,   65,   64,   65,
       68,   68,   64,  245,  245,  190,   65,   64,  245,  168,
       65,  191,   68,   68,  189,   65,   68,   68,   68,   68,
       64,   68,   68,  245,  170,   68,   68,  245,   65,  245,

       64,   68,   68,  245,   64,  173,   68,   68,   65,   64,
      195,  174,   65,   64,  245,   68,   68,   65,  193,  175,
      245,   65,   68,   68,   64,   68,   68,   68,   68,   64,
      245,  194,   65,   64,   68,   68,  196,   65,   68,   68,
       64,   65,  245,   68,   68,  202,  198,   64,   65,  245,
       64,  245,   64,  245,  245,   65,   68,   68,   65,  245,
       65,   64,  197,  181,  245,   64,   68,   68,  245,   65,
       68,   68,  245,   65,  199,   68,   68,   64,  245,   68,
       68,  201,  200,  245,  203,   65,  204,  245,  245,  245,
       68,   68,  245,  205,   64,   68,   68,  206,  245,   68,

       68,   64,   65,   64,  245,  245,   68,   68,  245,   65,
      245,   65,   64,   68,   68,   64,   68,   68,   68,   68,
       65,   64,  245,   65,  245,   64,  245,   68,   68,   65,
      209,   68,   68,   65,   64,  208,  245,   64,  210,   64,
      245,  245,   65,   68,   68,   65,  175,   65,   64,  245,
      245,   64,  245,  211,   64,  245,   65,  245,  213,   65,
       68,   68,   65,  245,   64,  245,   64,   68,   68,   68,
       68,  212,   65,  214,   65,  245,   64,  245,   68,   68,
      245,   68,   68,  245,   65,   64,  245,   68,   68,   64,
      245,   68,   68,   65,  216,  245,  245,   65,  245,   64,

       68,   68,   64,   68,   68,   68,   68,   65,  215,  245,
       65,   64,  245,  245,   68,   68,  245,   68,   68,   65,
       68,   68,  245,  245,  217,  245,  218,  221,   64,  245,
       68,   68,   68,   68,  205,  245,   65,   64,  245,  245,
       64,  245,   68,   68,  245,   65,   64,  219,   65,  245,
       64,   68,   68,   64,   65,   68,   68,  208,   65,  245,
      245,   65,  175,  245,  245,   68,   68,   64,   68,   68,
      245,  223,  222,  245,   64,   65,   64,   68,   68,   64,
      245,   64,   65,  211,   65,  245,  224,   65,   64,   65,
      245,  226,  214,  225,   68,   68,   65,   64,  227,  245,

      228,   64,  245,   68,   68,   65,   68,   68,  245,   65,
      245,  245,   68,   68,  245,  229,   68,   68,   64,   68,
       68,  245,  232,   64,  245,  245,   65,   64,  245,  231,
       64,   65,  245,   68,   68,   65,   64,  233,   65,  245,
       68,   68,   68,   68,   65,   68,   68,   68,   68,   64,
      245,   64,  245,   64,   68,   68,  234,   65,   64,   65,
      245,   65,   64,   68,   68,   64,   65,   68,   68,   64,
       65,   64,  245,   65,   64,  245,  225,   65,  235,   65,
       64,  245,   65,   64,   68,   68,  245,  245,   65,   68,
       68,   65,   64,   68,   68,  227,   68,   68,  245,  245,

       65,   64,   68,   68,  233,  245,   64,  238,  245,   65,
      228,  245,  245,  229,   65,   68,   68,   68,   68,   68,
       68,  245,  232,  237,   68,   68,   64,  245,   68,   68,
      234,   68,   68,  245,   65,   68,   68,   68,   68,  245,
       68,   68,  245,   64,  245,  240,   68,   68,   64,   68,
       68,   65,   64,  245,  245,   64,   65,   64,   68,   68,
       65,  245,   64,   65,  245,   65,  245,   68,   68,   64,
       65,  245,   68,   68,  243,  245,  245,   65,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,   68,   68,  245,  245,  245,  245,  245,  245,

      245,  245,  245,  245,  245,  245,  245,  241,  243,   68,
       68,  245,  245,  245,   68,   68,  245,  240,   68,   68,
      245,   68,   68,   68,   68,  245,  245,  245,   68,   68,
      245,  245,  245,  245,  245,   68,   68,   56,   56,   56,
       56,   56,   56,   59,   59,   59,   59,   66,   66,   66,
       66,   68,   68,  116,  116,  116,  116,  116,  116,   65,
       65,    5,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,

      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245
    } ;

static yyconst flex_int16_t yy_chk[1540] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    7,   18,    7,
        7,    9,    9,    9,    9,   11,   18,   11,   19,   59,
       20,   59,   21,  242,   22,  239,   19,   23,   20,  236,

       21,   25,   22,   61,   26,   23,   18,   21,   24,   25,
       61,   21,   26,   28,   62,   62,   24,   57,   27,   57,
       57,   28,   20,   26,   21,   31,   27,  230,   24,   23,
       25,   32,   22,   31,  116,  116,   24,   27,   37,   32,
      220,   29,   28,  207,   18,   18,   37,  192,   31,   29,
       32,  176,  118,   32,   19,   19,   20,   20,   21,   21,
       22,   22,   64,   23,   23,   63,   14,   25,   25,   29,
       26,   26,   13,   29,   24,   24,   29,   12,   30,   28,
       28,   33,    5,    0,   27,   27,   30,   34,    0,   33,
        0,   31,   31,   37,   35,   34,   33,   32,   32,    0,

        0,    0,   35,   36,   37,   37,   38,   29,   29,   35,
       30,   36,    0,   39,   38,    0,    0,   34,   40,    0,
       34,   39,    0,   41,    0,   36,   40,    0,   42,    0,
       43,   41,   44,    0,    0,   46,   42,    0,   43,    0,
       44,   45,    0,   46,   30,   30,    0,   33,   33,   45,
       49,    0,    0,   34,   34,   39,    0,   47,   49,   39,
       35,   35,    0,    0,   38,   47,    0,    0,   48,   36,
       36,   39,   38,   38,    0,   42,   48,    0,   44,   39,
       39,   41,   40,   42,   40,   40,   43,   45,    0,   41,
       41,   46,    0,    0,   42,   42,   43,   43,   44,   44,

       49,   46,   46,   50,    0,   51,    0,   45,   45,    0,
        0,   50,   47,   51,   53,   47,   49,   49,   47,   52,
        0,   66,   53,   47,   47,   54,   48,   52,   67,   66,
        0,   69,    0,   54,   48,   48,   67,   71,    0,   69,
       75,    0,    0,   70,    0,   71,   67,   51,   75,   50,
       69,   70,   50,   72,    0,    0,   53,    0,    0,    0,
       73,   72,    0,   71,    0,    0,    0,   74,   73,   50,
       50,   51,   51,    0,   54,   74,   52,   70,   52,    0,
       53,   53,   72,   73,    0,   52,   52,   66,   66,    0,
        0,   54,   54,   78,   67,   67,   74,   69,   69,    0,

        0,   78,    0,   71,   71,   77,   75,   75,   76,   70,
       70,    0,    0,   77,    0,   79,   76,   80,    0,   72,
       72,   81,    0,   79,    0,   80,   73,   73,   77,   81,
       82,    0,   78,   74,   74,   79,   76,   85,   82,   83,
        0,   76,   76,    0,   84,   85,   88,   83,   87,    0,
        0,   80,   84,    0,   88,   93,   87,   95,   85,   78,
       78,   89,   88,   93,    0,   95,    0,   84,   86,   89,
       90,   77,   77,   83,   76,   76,   86,   87,   90,   89,
        0,   79,   79,   80,   80,   94,    0,   81,   81,   90,
       91,    0,    0,   94,   86,    0,   82,   82,   91,   92,

       93,   96,   86,   85,   85,   83,   83,   92,    0,   96,
       84,   84,   88,   88,   87,   87,   91,   95,   92,    0,
        0,   93,   93,   95,   95,   97,    0,   89,   89,    0,
       98,   94,   99,   97,   86,   86,   90,   90,   98,    0,
       99,  102,    0,    0,    0,  100,    0,    0,    0,  102,
        0,   94,   94,  100,   96,    0,   91,   91,    0,    0,
        0,    0,    0,  101,    0,   92,   92,   96,   96,  103,
        0,  101,    0,    0,  104,    0,  106,  103,  105,    0,
       98,   97,  104,    0,  106,  107,  105,    0,   99,    0,
        0,   97,   97,  107,  108,    0,   98,   98,   99,   99,

      100,  109,  108,    0,  100,  100,  102,  102,  102,  109,
      110,  100,  100,  101,  111,    0,  103,  112,  110,  113,
        0,    0,  111,  114,    0,  112,  106,  113,    0,  101,
      101,  114,    0,  107,  104,  103,  103,    0,  105,    0,
      104,  104,  106,  106,  105,  105,    0,  108,  119,    0,
      120,  107,  107,  110,  108,    0,  119,  109,  120,  111,
      108,  108,  123,  112,    0,  120,    0,  109,  109,  114,
      123,    0,  113,    0,  122,    0,  110,  110,    0,  121,
      111,  111,  122,  112,  112,  113,  113,  121,  124,  114,
      114,  125,  123,  122,  121,    0,  124,  128,    0,  125,

      126,    0,    0,  127,    0,  128,    0,    0,  126,    0,
        0,  127,  130,    0,  119,  119,  120,  120,  125,  126,
      130,  124,  127,  129,    0,  131,  128,    0,  123,  123,
      132,  129,    0,  131,    0,  132,    0,    0,    0,  137,
      122,  122,  133,  132,  134,  121,  121,  137,  138,    0,
      133,  129,  134,    0,  124,  124,  138,  125,  125,  131,
      135,  133,    0,  128,  128,  136,  126,  126,  135,  127,
      127,  134,  139,  136,    0,  141,    0,    0,  130,  130,
      139,    0,  135,  141,  136,  138,  142,    0,  140,  129,
      129,  131,  131,    0,  142,    0,  140,    0,  139,  146,

        0,  132,  132,  140,  143,  137,  137,  146,  133,  133,
      134,  134,  143,    0,  138,  138,  144,    0,    0,    0,
      145,  142,  147,    0,  144,  148,  135,  135,  145,  150,
      147,  136,  136,  148,    0,  151,  143,  150,  139,  139,
      149,  141,  141,  151,    0,  146,    0,    0,  149,  152,
        0,    0,  142,  142,  140,  140,  153,  152,  144,  154,
        0,  158,  145,  155,  153,  146,  146,  154,  155,  158,
      143,  143,  156,    0,    0,  150,  155,  157,    0,  147,
      156,  151,  144,  144,  148,  157,  145,  145,  147,  147,
      159,  148,  148,    0,  149,  150,  150,    0,  159,    0,

      160,  151,  151,    0,  162,  152,  149,  149,  160,  161,
      158,  153,  162,  163,    0,  152,  152,  161,  156,  154,
        0,  163,  153,  153,  164,  154,  154,  158,  158,  166,
        0,  157,  164,  168,  155,  155,  159,  166,  156,  156,
      170,  168,    0,  157,  157,  166,  162,  165,  170,    0,
      167,    0,  169,    0,    0,  165,  159,  159,  167,    0,
      169,  171,  161,  160,    0,  172,  160,  160,    0,  171,
      162,  162,    0,  172,  163,  161,  161,  173,    0,  163,
      163,  165,  164,    0,  167,  173,  169,    0,    0,    0,
      164,  164,    0,  171,  174,  166,  166,  172,    0,  168,

      168,  175,  174,  177,    0,    0,  170,  170,    0,  175,
        0,  177,  179,  165,  165,  178,  167,  167,  169,  169,
      179,  180,    0,  178,    0,  181,    0,  171,  171,  180,
      178,  172,  172,  181,  182,  177,    0,  183,  180,  184,
        0,    0,  182,  173,  173,  183,  179,  184,  186,    0,
        0,  187,    0,  182,  185,    0,  186,    0,  184,  187,
      174,  174,  185,    0,  188,    0,  189,  175,  175,  177,
      177,  183,  188,  185,  189,    0,  190,    0,  179,  179,
        0,  178,  178,    0,  190,  194,    0,  180,  180,  191,
        0,  181,  181,  194,  187,    0,    0,  191,    0,  193,

      182,  182,  195,  183,  183,  184,  184,  193,  186,    0,
      195,  198,    0,    0,  186,  186,    0,  187,  187,  198,
      185,  185,    0,    0,  188,    0,  189,  194,  196,    0,
      188,  188,  189,  189,  190,    0,  196,  197,    0,    0,
      199,    0,  190,  190,    0,  197,  200,  191,  199,    0,
      205,  194,  194,  208,  200,  191,  191,  193,  205,    0,
        0,  208,  195,    0,    0,  193,  193,  204,  195,  195,
        0,  198,  196,    0,  201,  204,  202,  198,  198,  203,
        0,  206,  201,  197,  202,    0,  199,  203,  210,  206,
        0,  202,  200,  201,  196,  196,  210,  209,  203,    0,

      204,  211,    0,  197,  197,  209,  199,  199,    0,  211,
        0,    0,  200,  200,    0,  206,  205,  205,  212,  208,
      208,    0,  210,  213,    0,    0,  212,  214,    0,  209,
      215,  213,    0,  204,  204,  214,  216,  212,  215,    0,
      201,  201,  202,  202,  216,  203,  203,  206,  206,  217,
        0,  218,    0,  219,  210,  210,  213,  217,  223,  218,
        0,  219,  222,  209,  209,  221,  223,  211,  211,  225,
      222,  224,    0,  221,  226,    0,  215,  225,  216,  224,
      227,    0,  226,  228,  212,  212,    0,    0,  227,  213,
      213,  228,  229,  214,  214,  217,  215,  215,    0,    0,

      229,  232,  216,  216,  223,    0,  231,  226,    0,  232,
      218,    0,    0,  219,  231,  217,  217,  218,  218,  219,
      219,    0,  222,  221,  223,  223,  233,    0,  222,  222,
      224,  221,  221,    0,  233,  225,  225,  224,  224,    0,
      226,  226,    0,  234,    0,  231,  227,  227,  235,  228,
      228,  234,  237,    0,    0,  238,  235,  240,  229,  229,
      237,    0,  241,  238,    0,  240,    0,  232,  232,  243,
      241,    0,  231,  231,  238,    0,    0,  243,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  233,  233,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,  235,  241,  234,
      234,    0,    0,    0,  235,  235,    0,  237,  237,  237,
        0,  238,  238,  240,  240,    0,    0,    0,  241,  241,
        0,    0,    0,    0,    0,  243,  243,  246,  246,  246,
      246,  246,  246,  247,  247,  247,  247,  248,  248,  248,
      248,  249,  249,  250,  250,  250,  250,  250,  250,  251,
      251,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,

      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lex.l"
/*  lexer file
    author: dpatrickx*/
#line 5 "lex.l"
    #include "main.h"
    #include "yacc.tab.h"
    extern "C"
    {
        int yywrap(void);
        int yylex(void);
    }

#line 892 "lex.yy.c"

#define INITIAL 0
#define COMMENT 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 28 "lex.l"

#line 1082 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 246 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1462 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 29 "lex.l"
{   yylval.m_sId = ">";         return JUDGEOP;     }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 30 "lex.l"
{   yylval.m_sId = "<";         return JUDGEOP;     }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 31 "lex.l"
{   yylval.m_sId = "=";         return JUDGEOP;     }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 32 "lex.l"
{   yylval.m_sId = "inner";     return IOKIND;      }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 33 "lex.l"
{   yylval.m_sId = "outer";     return IOKIND;      }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 34 "lex.l"
{   yylval.m_sId = "and";       return CONNOP;      }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 35 "lex.l"
{   yylval.m_sId = "or";        return CONNOP;      }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 36 "lex.l"
{   yylval.m_sId = "not";       return CONNOP;      }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 37 "lex.l"
{   yylval.m_sId = "use";       return USE;         }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 38 "lex.l"
{   yylval.m_sId = "drop";      return DROP;        }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 39 "lex.l"
{   yylval.m_sId = "table";     return TABLE;       }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 40 "lex.l"
{   yylval.m_sId = "if";        return IF;          }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 41 "lex.l"
{   yylval.m_sId = "exists";    return EXISTS;      }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 42 "lex.l"
{   yylval.m_sId = "join";      return JOIN;        }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 43 "lex.l"
{   yylval.m_sId = "on";        return ON;          }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 44 "lex.l"
{   yylval.m_sId = "insert";    return INSERT;      }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 45 "lex.l"
{   yylval.m_sId = "into";      return INTO;        }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 46 "lex.l"
{   yylval.m_sId = "values";    return VALUES;      }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 47 "lex.l"
{   yylval.m_sId = "select";    return SELECT;      }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 48 "lex.l"
{   yylval.m_sId = "from";      return FROM;        }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 49 "lex.l"
{   yylval.m_sId = "where";     return WHERE;       }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 50 "lex.l"
{   yylval.m_sId = yytext;      return KIND;        }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 51 "lex.l"
{   yylval.m_sId = "delete";    return DELETE;      }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 52 "lex.l"
{   yylval.m_sId = "set";       return SET;         }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 53 "lex.l"
{   yylval.m_sId = "update";    return UPDATE;      }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 54 "lex.l"
{   yylval.m_sId = "create";    return CREATE;      }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 55 "lex.l"
{   yylval.m_sId = "primary";   return PRIMARY;     }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 56 "lex.l"
{   yylval.m_sId = "key";       return KEY;         }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 57 "lex.l"
{   yylval.m_sId = "not null";  return NOTNULL;     }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 58 "lex.l"
{   yylval.m_sId = "database";  return DATABASE;    }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 59 "lex.l"
{   yylval.m_sId = "show";      return SHOW;        }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 60 "lex.l"
{
            yylval.m_sId = yytext;
            return YIN;
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 64 "lex.l"
{
            yylval.m_sId = yytext;
            return TYPE;
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 68 "lex.l"
{
            yylval.m_sId = yytext;
            return VALUEIT;
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 72 "lex.l"
{
            yylval.m_sId = yytext;
            return IDENTIFIER;
        }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 76 "lex.l"
{
            yylval.m_sId = yytext;
            return (int)yytext[0];
        }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 80 "lex.l"
{
            yylval.m_sId = yytext;
            return EXPRESSION;
        }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 84 "lex.l"
{
            yylval.m_sId = yytext;
            return INTEGER;
        }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 88 "lex.l"
{}
	YY_BREAK
case 40:
/* rule 40 can match eol */
YY_RULE_SETUP
#line 89 "lex.l"
{}
	YY_BREAK
case 41:
/* rule 41 can match eol */
YY_RULE_SETUP
#line 90 "lex.l"
{}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 92 "lex.l"
{
            yylval.m_cOp=yytext[0];
            return OPERATOR;
        }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 97 "lex.l"
ECHO;
	YY_BREAK
#line 1406 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 246 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 246 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 245);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 97 "lex.l"


int yywrap(void)
{
    puts("-----the file is end");
    return 1;
}
